"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { scenarioTypes, sports } from "@/lib/content";
import { supabase } from "@/lib/supabase-browser";
import styles from "./studio.module.css";

type Section = { id: string; heading: string; body: string; premium: boolean; imageUrl?: string; imageAlt: string; imageCaption: string; imageFileName: string };
type DraftStatus = "Draft"|"In Review"|"Changes Requested"|"Approved"|"Scheduled"|"Published"|"Archived";
type Draft = { articleId?:string; title:string; subtitle:string; slug:string; sport:string; scenarioType:string; tags:string; excerpt:string; heroAlt:string; heroFileName:string; heroUrl?:string; seoTitle:string; seoDescription:string; editorFeedback:string; status:DraftStatus; sections:Section[] };
type Profile = { id:string; display_name:string; role:"admin"|"editor"|"contributor"; is_active:boolean; application_status?:"pending"|"approved"|"declined" };

const KEY="sports-rewritten-contributor-draft-v3";
const initial:Draft={title:"",subtitle:"",slug:"",sport:"College Football",scenarioType:"Born in Another Era",tags:"",excerpt:"",heroAlt:"",heroFileName:"",seoTitle:"",seoDescription:"",editorFeedback:"",status:"Draft",sections:[{id:"s1",heading:"The Player We Actually Got",body:"",premium:false,imageUrl:undefined,imageAlt:"",imageCaption:"",imageFileName:""},{id:"s2",heading:"The Divergence",body:"",premium:false,imageUrl:undefined,imageAlt:"",imageCaption:"",imageFileName:""}]};
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const dbStatus=(s:DraftStatus)=>({"Draft":"draft","In Review":"in_review","Changes Requested":"changes_requested","Approved":"approved","Scheduled":"scheduled","Published":"published","Archived":"archived"}[s]);
const uiStatus=(s:string):DraftStatus=>({draft:"Draft",in_review:"In Review",changes_requested:"Changes Requested",approved:"Approved",scheduled:"Scheduled",published:"Published",archived:"Archived"}[s] as DraftStatus)||"Draft";

export function StudioEditor(){
 const [draft,setDraft]=useState<Draft>(initial); const [ready,setReady]=useState(false); const [savedAt,setSavedAt]=useState(""); const [preview,setPreview]=useState(false); const [hero,setHero]=useState(""); const [heroFile,setHeroFile]=useState<File|null>(null); const [sectionImageFiles,setSectionImageFiles]=useState<Record<string,File>>({}); const [sectionImagePreviews,setSectionImagePreviews]=useState<Record<string,string>>({});
 const [userId,setUserId]=useState<string|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [displayName,setDisplayName]=useState(""); const [authMode,setAuthMode]=useState<"signin"|"signup">("signin"); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [loadedTarget,setLoadedTarget]=useState(false);

 useEffect(()=>{const s=localStorage.getItem(KEY); if(s){try{setDraft(JSON.parse(s))}catch{localStorage.removeItem(KEY)}} setReady(true); void syncSession(); const {data}=supabase.auth.onAuthStateChange(()=>{void syncSession()}); return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!ready)return; const t=setTimeout(()=>{localStorage.setItem(KEY,JSON.stringify(draft)); setSavedAt(new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}))},450); return()=>clearTimeout(t)},[draft,ready]);
 useEffect(()=>{if(!userId||!profile||loadedTarget)return; const id=new URLSearchParams(window.location.search).get("article"); if(id) void loadArticle(id); else {setDraft(d=>d.articleId?{...initial}:({...d,status:"Draft",editorFeedback:""})); setLoadedTarget(true)}},[userId,profile,loadedTarget]);
 const words=useMemo(()=>[draft.title,draft.subtitle,draft.excerpt,...draft.sections.map(s=>s.body)].join(" ").trim().split(/\s+/).filter(Boolean).length,[draft]);
 const field=<K extends keyof Draft>(k:K,v:Draft[K])=>setDraft(d=>({...d,[k]:v}));
 const updateSection=(id:string,p:Partial<Section>)=>setDraft(d=>({...d,sections:d.sections.map(s=>s.id===id?{...s,...p}:s)}));
 const add=()=>setDraft(d=>({...d,sections:[...d.sections,{id:crypto.randomUUID(),heading:"New Section",body:"",premium:true,imageUrl:undefined,imageAlt:"",imageCaption:"",imageFileName:""}]}));
 const sectionImageSource=(s:Section)=>sectionImagePreviews[s.id]||s.imageUrl||"";
 const chooseSectionImage=(id:string,file:File)=>{setSectionImageFiles(v=>({...v,[id]:file}));setSectionImagePreviews(v=>({...v,[id]:URL.createObjectURL(file)}));updateSection(id,{imageFileName:file.name})};
 const clearSectionImage=(id:string)=>{setSectionImageFiles(v=>{const n={...v};delete n[id];return n});setSectionImagePreviews(v=>{const n={...v};delete n[id];return n});updateSection(id,{imageUrl:undefined,imageAlt:"",imageCaption:"",imageFileName:""})};
 const isStaff=profile?.role==="admin"||profile?.role==="editor";
 const canEdit=!!profile?.is_active&&(isStaff||!draft.articleId||draft.status==="Draft"||draft.status==="Changes Requested");

 async function syncSession(){ const {data:{user}}=await supabase.auth.getUser(); setUserId(user?.id??null); if(!user){setProfile(null);setLoadedTarget(false);return} const {data}=await supabase.from("profiles").select("id,display_name,role,is_active,application_status").eq("id",user.id).maybeSingle(); setProfile(data as Profile|null); }
 async function handleAuth(e:FormEvent){e.preventDefault();setBusy(true);setMessage(""); if(authMode==="signup"){const {error}=await supabase.auth.signUp({email,password,options:{data:{display_name:displayName}}}); setMessage(error?error.message:"Account created. Check your email if confirmation is required. Contributor access remains pending until an editor approves your account.");} else {const {error}=await supabase.auth.signInWithPassword({email,password}); setMessage(error?error.message:"Signed in.");} setBusy(false); await syncSession();}

 async function loadArticle(articleId:string){
  setBusy(true); setMessage("Loading article…");
  const {data:a,error:aError}=await supabase.from("articles").select("id,title,slug,subtitle,excerpt,sport,scenario_type,hero_image_url,hero_image_alt,status,seo_title,seo_description,editor_notes,author_id").eq("id",articleId).maybeSingle();
  if(aError||!a){setMessage(aError?.message||"Article not found or you do not have permission to open it.");setBusy(false);setLoadedTarget(true);return}
  const {data:s,error:sError}=await supabase.from("article_sections").select("id,heading,body,is_premium,display_order,image_url,image_alt,image_caption").eq("article_id",articleId).order("display_order",{ascending:true});
  if(sError){setMessage(sError.message);setBusy(false);setLoadedTarget(true);return}
  setDraft({articleId:a.id,title:a.title??"",subtitle:a.subtitle??"",slug:a.slug??"",sport:a.sport??"College Football",scenarioType:a.scenario_type??"Born in Another Era",tags:"",excerpt:a.excerpt??"",heroAlt:a.hero_image_alt??"",heroFileName:"",heroUrl:a.hero_image_url??undefined,seoTitle:a.seo_title??"",seoDescription:a.seo_description??"",editorFeedback:a.editor_notes??"",status:uiStatus(a.status),sections:(s??[]).map((x:any)=>({id:x.id,heading:x.heading??"",body:x.body??"",premium:!!x.is_premium,imageUrl:x.image_url??undefined,imageAlt:x.image_alt??"",imageCaption:x.image_caption??"",imageFileName:""}))});
  setHero(""); setHeroFile(null); setSectionImageFiles({}); setSectionImagePreviews({}); setSavedAt("cloud loaded"); setMessage(a.status==="changes_requested"&&a.editor_notes?"Revision requested. Review the editor feedback before resubmitting.":"Article loaded from Sports Rewritten cloud storage."); setBusy(false); setLoadedTarget(true);
 }

 async function uploadHero(articleId:string){if(!heroFile||!userId)return draft.heroUrl??null; const ext=heroFile.name.split('.').pop()?.toLowerCase()||'jpg'; const path=`${userId}/${articleId}/hero-${Date.now()}.${ext}`; const {error}=await supabase.storage.from("article-media").upload(path,heroFile,{upsert:true}); if(error)throw error; return supabase.storage.from("article-media").getPublicUrl(path).data.publicUrl;}
 async function uploadSectionImage(articleId:string,section:Section,index:number){const file=sectionImageFiles[section.id];if(!file||!userId)return section.imageUrl??null;const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${userId}/${articleId}/section-${String(index+1).padStart(2,"0")}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from("article-media").upload(path,file,{upsert:true});if(error)throw error;return supabase.storage.from("article-media").getPublicUrl(path).data.publicUrl;}
 async function saveCloud(nextStatus?:"draft"|"in_review"){
  if(!userId||!profile?.is_active){setMessage("Your contributor account must be approved before cloud publishing tools are enabled.");return}
  if(!draft.title.trim()||!draft.slug.trim()){setMessage("Add a headline and slug first.");return}
  if(!canEdit){setMessage("This article is locked at its current editorial status.");return}
  setBusy(true);setMessage("");
  try{
   const editingStatus=!isStaff&&draft.status==="Changes Requested"?"changes_requested":(!isStaff?"draft":dbStatus(draft.status));
   const basePayload={title:draft.title,slug:draft.slug,subtitle:draft.subtitle||null,excerpt:draft.excerpt||null,sport:draft.sport,scenario_type:draft.scenarioType,status:editingStatus,access_level:"premium",estimated_read_time:Math.max(1,Math.ceil(words/225)),seo_title:draft.seoTitle||null,seo_description:draft.seoDescription||null,hero_image_alt:draft.heroAlt||null};
   let articleId=draft.articleId;
   if(articleId){
    const {error}=await supabase.from("articles").update(basePayload).eq("id",articleId); if(error)throw error;
   } else {
    const {data,error}=await supabase.from("articles").insert({...basePayload,author_id:userId,author_name:profile.display_name,status:"draft"}).select("id").single(); if(error)throw error; articleId=data.id;
    window.history.replaceState(null,"",`/studio?article=${articleId}`);
   }
   const heroUrl=await uploadHero(articleId!);
   if(heroUrl){const {error}=await supabase.from("articles").update({hero_image_url:heroUrl}).eq("id",articleId); if(error)throw error;}
   const {error:delErr}=await supabase.from("article_sections").delete().eq("article_id",articleId); if(delErr)throw delErr;
   const rows=await Promise.all(draft.sections.map(async(s,i)=>({article_id:articleId,heading:s.heading,body:s.body,is_premium:s.premium,display_order:i,section_type:"standard",image_url:await uploadSectionImage(articleId!,s,i),image_alt:s.imageAlt||null,image_caption:s.imageCaption||null})));
   if(rows.length){const {error}=await supabase.from("article_sections").insert(rows); if(error)throw error;}
   if(nextStatus==="in_review"){
    const {error}=await supabase.from("articles").update({status:"in_review",submitted_at:new Date().toISOString()}).eq("id",articleId); if(error)throw error;
   }
   const nextUi=nextStatus==="in_review"?"In Review":draft.status;
   setDraft(d=>({...d,articleId,heroUrl:heroUrl??d.heroUrl,status:nextUi}));
   setSavedAt("cloud saved");
   setMessage(nextStatus==="in_review"?(draft.status==="Changes Requested"?"Revisions resubmitted for editorial review.":"Article submitted for editorial review."):"Article saved to Sports Rewritten cloud storage.");
  }catch(err){setMessage(err instanceof Error?err.message:"Unable to save article.");} finally{setBusy(false)}
 }
 async function submit(){if(!draft.title.trim()||!draft.excerpt.trim()||draft.sections.some(s=>!s.body.trim())){setMessage("Add a headline, excerpt, and content to every section before submitting for review.");return} await saveCloud("in_review")}

 if(!userId)return <section className={`shell ${styles.studioShell}`}><div className={styles.authCard}><p className="goldKicker">CONTRIBUTOR ACCESS</p><h2>{authMode==="signin"?"Sign in to Contributor Studio":"Request contributor access"}</h2><p>Approved contributors can save cloud drafts, upload hero images, preview stories, and submit work for editorial review.</p><form onSubmit={handleAuth}>{authMode==="signup"&&<label>Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label><button className="redButton" disabled={busy}>{busy?"Working…":authMode==="signin"?"Sign In":"Create Account"}</button></form><button className={styles.textButton} type="button" onClick={()=>setAuthMode(authMode==="signin"?"signup":"signin")}>{authMode==="signin"?"Need contributor access? Create an account":"Already have an account? Sign in"}</button>{message&&<p className={styles.message}>{message}</p>}</div></section>;
 if(profile&&!profile.is_active)return <section className={`shell ${styles.studioShell}`}><div className={styles.authCard}><p className="goldKicker">ACCOUNT {profile.application_status==="declined"?"DECLINED":"PENDING"}</p><h2>{profile.application_status==="declined"?"Contributor access declined":"Contributor approval required"}</h2><p>{profile.application_status==="declined"?"This contributor application has not been approved.":"Your account exists, but an editor must approve it before you can save or submit Sports Rewritten articles."}</p><button className="outlineButton" onClick={()=>supabase.auth.signOut()}>Sign Out</button></div></section>;

 return <section className={`shell ${styles.studioShell}`}>
  <div className={styles.statusBar}><div><span className={styles.status}>{draft.status}</span><span>{savedAt?`Saved ${savedAt}`:"Cloud save ready"}</span><span>{words} words</span><span>{Math.max(1,Math.ceil(words/225))} min read</span></div><p>{profile?.display_name} • {profile?.role}</p></div>{message&&<p className={styles.message}>{message}</p>}
  {draft.editorFeedback&&<div className={styles.card}><p className="goldKicker">EDITOR FEEDBACK</p><p style={{whiteSpace:"pre-wrap",lineHeight:1.65}}>{draft.editorFeedback}</p></div>}
  <div className={styles.toolbar}><button className="outlineButton" type="button" disabled={busy||!canEdit} onClick={()=>void saveCloud()}>{busy?"Saving…":draft.status==="Published"?"Save Published Changes":"Save Cloud Draft"}</button><button className="outlineButton" type="button" onClick={()=>setPreview(v=>!v)}>{preview?"Edit Article":"Preview Article"}</button>{draft.status!=="Published"&&draft.status!=="Scheduled"&&<button className="redButton" type="button" disabled={busy||!canEdit} onClick={()=>void submit()}>{draft.status==="Changes Requested"?"Resubmit for Review":"Submit for Review"}</button>}<button className={styles.textButton} type="button" onClick={()=>supabase.auth.signOut()}>Sign Out</button></div>{isStaff&&draft.status==="Published"&&<p className={styles.publishedEditNote}>This story is live. Editors can change text, the hero image, or section photos here; saving keeps it published.</p>}
  {preview?<article className={styles.preview}><p className="eyebrow">{draft.sport.toUpperCase()} • {draft.scenarioType.toUpperCase()}</p><h1>{draft.title||"Untitled Sports Rewritten Story"}</h1><p className={styles.previewSubtitle}>{draft.subtitle||"Add a subtitle to frame the alternate timeline."}</p>{hero||draft.heroUrl?<img className={styles.previewHero} src={hero||draft.heroUrl} alt={draft.heroAlt||"Draft hero preview"}/>:<div className={styles.heroPlaceholder}>HERO IMAGE PREVIEW</div>}<p className={styles.previewExcerpt}>{draft.excerpt||"Your article excerpt will appear here."}</p>{draft.sections.map((s,i)=><section className={styles.previewSection} key={s.id}><span>{String(i+1).padStart(2,"0")}</span><div><div className={styles.sectionHeadingRow}><h2>{s.heading}</h2>{s.premium&&<small>PREMIUM</small>}</div>{sectionImageSource(s)&&<figure className={styles.previewSectionFigure}><img src={sectionImageSource(s)} alt={s.imageAlt||s.heading}/>{s.imageCaption&&<figcaption>{s.imageCaption}</figcaption>}</figure>}<p>{s.body||"Section copy will appear here."}</p></div></section>)}</article>:
  <div className={styles.editorGrid}><div className={styles.editorMain}><div className={styles.card}><p className="goldKicker">STORY BASICS</p><label>Headline<input value={draft.title} disabled={!canEdit} onChange={e=>setDraft(d=>({...d,title:e.target.value,slug:d.slug&&d.slug!==slugify(d.title)?d.slug:slugify(e.target.value),seoTitle:d.seoTitle||e.target.value}))}/></label><label>Subtitle / Deck<textarea rows={3} value={draft.subtitle} disabled={!canEdit} onChange={e=>field("subtitle",e.target.value)}/></label><div className={styles.twoColumns}><label>Sport<select value={draft.sport} disabled={!canEdit} onChange={e=>field("sport",e.target.value)}>{sports.map(x=><option key={x}>{x}</option>)}</select></label><label>Scenario Type<select value={draft.scenarioType} disabled={!canEdit} onChange={e=>field("scenarioType",e.target.value)}>{scenarioTypes.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Slug<input value={draft.slug} disabled={!canEdit} onChange={e=>field("slug",slugify(e.target.value))}/></label><label>Tags<input value={draft.tags} disabled={!canEdit} onChange={e=>field("tags",e.target.value)} placeholder="Joe Hamilton, Georgia Tech, NFL Draft"/></label><label>Article Excerpt<textarea rows={4} value={draft.excerpt} disabled={!canEdit} onChange={e=>field("excerpt",e.target.value)}/></label></div>
  <div className={styles.card}><div className={styles.cardHeading}><div><p className="goldKicker">ARTICLE BODY</p><h2>Timeline Sections</h2></div><button type="button" className="outlineButton" disabled={!canEdit} onClick={add}>+ Add Section</button></div><div className={styles.sections}>{draft.sections.map((s,i)=><div className={styles.sectionEditor} key={s.id}><div className={styles.sectionTop}><strong>{String(i+1).padStart(2,"0")}</strong><input value={s.heading} disabled={!canEdit} onChange={e=>updateSection(s.id,{heading:e.target.value})}/><label className={styles.check}><input type="checkbox" checked={s.premium} disabled={!canEdit} onChange={e=>updateSection(s.id,{premium:e.target.checked})}/> Premium</label>{draft.sections.length>1&&<button type="button" disabled={!canEdit} onClick={()=>setDraft(d=>({...d,sections:d.sections.filter(x=>x.id!==s.id)}))}>Remove</button>}</div><textarea rows={10} value={s.body} disabled={!canEdit} onChange={e=>updateSection(s.id,{body:e.target.value})}/><div className={styles.sectionMedia}><div><label className={styles.sectionUpload}>Add / replace section photo<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" disabled={!canEdit} onChange={e=>{const file=e.target.files?.[0];if(file)chooseSectionImage(s.id,file)}}/></label>{sectionImageSource(s)&&<><img className={styles.sectionImagePreview} src={sectionImageSource(s)} alt={s.imageAlt||s.heading}/><button type="button" className={styles.removeMedia} disabled={!canEdit} onClick={()=>clearSectionImage(s.id)}>Remove section photo</button></>}</div><div className={styles.sectionImageFields}><label>Photo Alt Text<input value={s.imageAlt} disabled={!canEdit} onChange={e=>updateSection(s.id,{imageAlt:e.target.value})}/></label><label>Photo Caption<input value={s.imageCaption} disabled={!canEdit} onChange={e=>updateSection(s.id,{imageCaption:e.target.value})}/></label><small>{s.imageFileName||"Optional image for this section. Editors may replace it after publication."}</small></div></div></div>)}</div></div></div>
  <aside className={styles.editorRail}><div className={styles.card}><p className="goldKicker">HERO ART</p><label className={styles.uploadBox}>Choose hero image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" disabled={!canEdit} onChange={e=>{const f=e.target.files?.[0]; if(!f)return; setHeroFile(f); setHero(URL.createObjectURL(f)); field("heroFileName",f.name)}}/></label>{(hero||draft.heroUrl)&&<img src={hero||draft.heroUrl} className={styles.railImage} alt="Hero image preview"/>}<small>{draft.heroFileName||"PNG, JPEG, WebP, or GIF. Maximum 10 MB."}</small><label>Image Alt Text<textarea rows={3} value={draft.heroAlt} disabled={!canEdit} onChange={e=>field("heroAlt",e.target.value)}/></label></div><div className={styles.card}><p className="goldKicker">SEARCH & DISCOVERY</p><label>SEO Title<input value={draft.seoTitle} disabled={!canEdit} onChange={e=>field("seoTitle",e.target.value)}/></label><label>SEO Description<textarea rows={4} value={draft.seoDescription} disabled={!canEdit} onChange={e=>field("seoDescription",e.target.value)}/></label></div></aside></div>}
 </section>
}
