"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase-browser";

type Subscription={plan_code:string;status:string;current_period_end:string|null;cancel_at_period_end:boolean};

export function MembershipAccount(){
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [displayName,setDisplayName]=useState("");
 const [mode,setMode]=useState<"signin"|"signup">("signin"); const [userEmail,setUserEmail]=useState<string|null>(null); const [subscription,setSubscription]=useState<Subscription|null>(null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{void sync();const {data}=supabase.auth.onAuthStateChange(()=>void sync());return()=>data.subscription.unsubscribe()},[]);
 async function sync(){const {data:{user}}=await supabase.auth.getUser();setUserEmail(user?.email??null);if(!user){setSubscription(null);return}const {data}=await supabase.from("subscriptions").select("plan_code,status,current_period_end,cancel_at_period_end").in("status",["active","trialing","past_due"]).order("created_at",{ascending:false}).limit(1).maybeSingle();setSubscription(data as Subscription|null)}
 async function auth(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");if(mode==="signup"){const {error}=await supabase.auth.signUp({email,password,options:{data:{display_name:displayName,account_type:"reader"}}});setMessage(error?error.message:"Reader account created. Check your email if confirmation is required.")}else{const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?error.message:"Signed in.")}setBusy(false);await sync()}
 if(userEmail)return <div style={{border:"1px solid rgba(255,255,255,.14)",background:"#11181b",padding:22,marginTop:28}}><p className="goldKicker">READER ACCOUNT</p><h3 style={{margin:"6px 0 8px"}}>{userEmail}</h3>{subscription?<p>Membership: <strong>{subscription.plan_code.replace("_"," ")}</strong> · {subscription.status}{subscription.current_period_end?` through ${new Date(subscription.current_period_end).toLocaleDateString()}`:""}</p>:<p style={{color:"#aeb7bb"}}>No active membership yet. Checkout will be enabled when Stripe is connected.</p>}<button className="outlineButton" onClick={()=>supabase.auth.signOut()}>Sign Out</button></div>;
 return <div style={{border:"1px solid rgba(255,255,255,.14)",background:"#11181b",padding:22,marginTop:28,maxWidth:620}}><p className="goldKicker">READER ACCOUNT</p><h3>{mode==="signin"?"Sign in":"Create a reader account"}</h3><form onSubmit={auth} style={{display:"grid",gap:12}}>{mode==="signup"&&<label>Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required style={{display:"block",width:"100%",padding:12,marginTop:6,boxSizing:"border-box"}}/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required style={{display:"block",width:"100%",padding:12,marginTop:6,boxSizing:"border-box"}}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} style={{display:"block",width:"100%",padding:12,marginTop:6,boxSizing:"border-box"}}/></label><button className="redButton" disabled={busy}>{busy?"Working…":mode==="signin"?"Sign In":"Create Reader Account"}</button></form><button type="button" onClick={()=>setMode(mode==="signin"?"signup":"signin")} style={{background:"none",border:0,color:"#c8a95b",padding:"14px 0 0",cursor:"pointer"}}>{mode==="signin"?"New reader? Create an account":"Already have an account? Sign in"}</button>{message&&<p>{message}</p>}</div>
}
